### PR TITLE
Goal Feature: Update DG

### PR DESCRIPTION
**Pull request by mgiang2015**
Update DG for `Goal` Feature, including diagrams

### CODE REVIEW

**Review by pennhanlee — COMMENTED** [review]
For GoalClassDiagram.puml, will it be better to follow the hierarchal order and put the interface ontop of the implemented class?

**Review by TanLeYang — COMMENTED** [review]
Lgtm!

**Comment by angrybunny123** [comment]
LGTM!

**Comment by mgiang2015** [comment]
> For GoalClassDiagram.puml, will it be better to follow the hierarchal order and put the interface ontop of the implemented class?

Updated diagram to follow hierarchal order

**Pull request merged**
